---

jobs:
- name: job-deploy-kafka-manager
  public: true
  serial: true
  plan:
    - task: job-deploy-kafka-manager
      file: resource-bidskafkapoc/source/ci/kafka-manager/tasks/deploy-kafka-manager.yml
      params:
        k8s_cluster_ca: {{kubernetes_cluster_ca}}
        k8s_admin_key: {{kubernetes_admin_key}}
        k8s_admin_cert: {{kubernetes_admin_cert}}

