---
apiVersion: v1
kind: Service
metadata:
  name: poc-kafka-source-service
  labels:
    app: kafka
spec:
  ports:
  - port: 80
    name: poc-kafka-source-port
    targetPort: 8090
    protocol: TCP
  selector:
    app: poc-kafka-source
  type: LoadBalancer