---
apiVersion: v1
kind: Service
metadata:
  name: poc-kafka-source-service
  labels:
    app: poc-kafka-source
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: poc-kafka-source
  type: LoadBalancer