platform: linux

image_resource:
  type: docker-image
  source: {repository: wernight/kubectl}

inputs:
  - name: resource-bidskafkapoc
  - name: bidskafkapoc-docker-image

outputs:
  - name: resource-k8s

run:
  path: ./resource-bidskafkapoc/sink/ci/scripts/deploy.sh
  user: root

