---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-rc${n}
  labels:
    name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-node${n}
  template:
    metadata:
      labels:
        name: mongo-node${n}
        instance: mongo-node${n}
    spec:
      containers:
      - name: mongo-node${n}
        image: mongo
        command:
        - mongod
        - "--replSet"
        - my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage${n}
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage${n}
        awsElasticBlockStore:
          volumeID: ${volumeID}
          fsType: ext4