---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-null
  labels:
    name: mongo-svc-null
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    mongo-rs-name: mongo
