# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: false
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000


spring:
    data:
        mongodb:
            uri: mongodb://a696c8c01713411e6aebc0a99633e5c2-1573676446.us-east-1.elb.amazonaws.com:27017,a698511cb713411e6aebc0a99633e5c2-2071484494.us-east-1.elb.amazonaws.com:27017,a699f9f2a713411e6aebc0a99633e5c2-892234296.us-east-1.elb.amazonaws.com:27017/bidstats
            repositories.enabled: true
    mvc:
        favicon:
            enabled: false
    cloud:
        stream:
            bindings:
                bids:
                    group: bidsgr
                bidstats:
                    group: bidstatsgr
            kafka:
                binder:
                    brokers: ae920f55667d011e6bb0a0a115674f32-134534388.us-east-1.elb.amazonaws.com:9092
                    zkNodes: a28b990ad67d011e6bb0a0a115674f32-870432376.us-east-1.elb.amazonaws.com:2181, a28c4de0267d011e6bb0a0a115674f32-1462874061.us-east-1.elb.amazonaws.com:2181, a28d1fd5a67d011e6bb0a0a115674f32-490104583.us-east-1.elb.amazonaws.com:2181
                bindings:
                    bids:
                        consumer:
                            a: b
#                            startOffset: earliest
#                            resetOffsets: true
                    bidstats:
                        consumer:
                            a: b
#                            startOffset: earliest
#                            resetOffsets: true

swagger:
    title: bidskafkapoc API
    description: bidskafkapoc applications and beyond!
    version: 0.0.1
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

