---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ${APP_NAME}-controller
spec:
  replicas: 3
  selector:
    app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${DEPLOY_IMAGE_NAME}
        ports:
        - containerPort: ${APP_PORT}
        env:
        - name: MY_VAR
          value: "test"
