---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  labels:
    app: ${APP_NAME}
spec:
  ports:
  - port: ${APP_PORT}
    targetPort: ${APP_PORT}
  selector:
    app: ${APP_NAME}
#  type: LoadBalancer