---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-${n}
  labels:
    app: kafka-${n}
    kafka-cluster: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-${n}
  type: LoadBalancer