---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc-null
  labels:
    name: zookeeper-svc-null
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    zookeeper-cl-name: zookeeper