platform: linux

image_resource:
  type: docker-image
  source: {repository: imuntyan/gradle, tag: v1}

inputs:
  - name: resource-bidskafkapoc
  - name: bidskafkapoc-docker-image

outputs:
  - name: resource-k8s

params:
  k8s_ip:
  k8s_dns_name:

run:
  path: ./resource-bidskafkapoc/source/ci/scripts/deploy.sh

