platform: linux

image_resource:
  type: docker-image
  source: {repository: imuntyan/gradle, tag: v1}

inputs:
  - name: resource-bidskafkapoc
  - name: resource-jar

outputs:
  - name: resource-k8s

run:
  path: ./resource-bidskafkapoc/source/ci/scripts/deploy.sh

