platform: linux

image_resource:
  type: docker-image
  #source: {repository: imuntyan/gradle, tag: v1}
  source: {repository: wernight/kubectl}

inputs:
  - name: resource-bidskafkapoc
  - name: bidskafkapoc-docker-image

outputs:
  - name: resource-k8s

params:
  k8s_ip:
  k8s_dns_name:
  k8s_cluster_ca:
  k8s_admin_key:
  k8s_admin_cert:

run:
  path: ./resource-bidskafkapoc/source/ci/scripts/deploy.sh
  user: root

