platform: linux

image_resource:
  type: docker-image
  source: {repository: imuntyan/gradle, tag: v1}

inputs:
  - name: k8s_input

outputs:
  - name: k8s_output

run:
  path: ./resource-bidskafkapoc/source/ci/scripts/deploy.sh

